package com.d3velopers.sms_search.dao.pojos;
// Generated Apr 14, 2012 12:14:54 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Query generated by hbm2java
 */
@Entity
@Table(name="query"
    ,catalog="sms_search"
)
public class Query  implements java.io.Serializable {


     private Integer id;
     private String query;
     private String phoneNumber;
     private String queryType;
     private Date dateCreated;
     private Set<Response> responses = new HashSet<Response>(0);

    public Query() {
    }

	
    public Query(String query, String phoneNumber, String queryType, Date dateCreated) {
        this.query = query;
        this.phoneNumber = phoneNumber;
        this.queryType = queryType;
        this.dateCreated = dateCreated;
    }
    public Query(String query, String phoneNumber, String queryType, Date dateCreated, Set<Response> responses) {
       this.query = query;
       this.phoneNumber = phoneNumber;
       this.queryType = queryType;
       this.dateCreated = dateCreated;
       this.responses = responses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="Query", nullable=false, length=200)
    public String getQuery() {
        return this.query;
    }
    
    public void setQuery(String query) {
        this.query = query;
    }
    
    @Column(name="PhoneNumber", nullable=false, length=16)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    
    @Column(name="QueryType", nullable=false)
    public String getQueryType() {
        return this.queryType;
    }
    
    public void setQueryType(String queryType) {
        this.queryType = queryType;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateCreated", nullable=false, length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="query")
    public Set<Response> getResponses() {
        return this.responses;
    }
    
    public void setResponses(Set<Response> responses) {
        this.responses = responses;
    }




}


